article/urls.py
from django.conf.urls import patterns, include, url
from api import ArticleResource

article_resource = ArticleResource()

urlpatterns = patterns('',

	url(r'^all/$', 'article.views.articles'),
	url(r'^get/(?P<article_id>\d+)/$', 'article.views.article'),
	url(r'^language/(?P<language>[a-z\-]+)/$', 'article.views.language'),
	url(r'^create/$', 'article.views.create'),
	url(r'^like/(?P<article_id>\d+)/$', 'article.views.like_article'),
	url(r'^add_comment/(?P<article_id>\d+)/$', 'article.views.add_comment'),
	url(r'^search/$', 'article.views.search_titles'),	
	url(r'^api/', include(article_resource.urls)),
	url(r'^push/$', 'article.views.push'),
)

django_test/urls.py
from django.conf.urls import patterns, include, url
from article.views import HelloTemplate
from django.contrib import admin
from tastypie.api import Api

from django_test.forms import ContactForm3, ContactForm2, ContactForm1
from django_test.views import ContactWizard

admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'django_test.views.index'),
	(r'^articles/', include('article.urls')),
	(r'^accounts/', include('userprofile.urls')),
# admin
    url(r'^admin/', include(admin.site.urls)),

# user auth & registration
	url(r'^accounts/login/$', 'django_test.views.login'),
	url(r'^accounts/auth/$', 'django_test.views.auth_view'),
	url(r'^accounts/logout/$', 'django_test.views.logout'),
	url(r'^accounts/loggedin/$', 'django_test.views.loggedin'),
	url(r'^accounts/invalid/$', 'django_test.views.invalid_login'),
	url(r'^accounts/register/$', 'django_test.views.register_user'),
	url(r'^accounts/register_success/$', 'django_test.views.register_success'),
    url(r'^contact/$', ContactWizard.as_view([ContactForm1, ContactForm2, ContactForm3])),

# Hello examples
	url(r'hello/$', 'article.views.hello'),
	url(r'hello_template/$', 'article.views.hello_template'),
	url(r'hello_bootstrap/$', 'article.views.hello_bootstrap'),
	url(r'hello_template_simple/$', 'article.views.hello_template_simple'),
	url(r'hello_class_view/$', HelloTemplate.as_view()),

)

article/models.py
from django.db import models
from time import time

def get_upload_file_name(instance, filename):
	return "uploaded_files/%s_%s" % (str(time()).replace('.','_'), filename)

# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length=200)
	body = models.TextField()
	pub_date = models.DateTimeField('date published')
	likes = models.IntegerField(default=0)
	thumbnail = models.FileField(upload_to=get_upload_file_name, blank=True)

	def __unicode__(self):
		return self.title

class Comment(models.Model):
	name = models.CharField(max_length=200)
	body = models.TextField()
	pub_date = models.DateTimeField('date published')
	article = models.ForeignKey(Article)
	likes = models.IntegerField(default=0)

	def __unicode__(self):
		return self.name

article/forms.py
from django import forms
from models import Article, Comment

class ArticleForm(forms.ModelForm):
	
	class Meta:
		model = Article
		fields = ('title', 'body', 'pub_date', 'thumbnail')

class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = ('name', 'body')

article/views.py
from django.shortcuts import render_to_response
from article.models import Article
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from forms import ArticleForm
from django.core.context_processors import csrf

from django.template.loader import get_template
from django.template import Context
from django.template import RequestContext
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.decorators.csrf import csrf_exempt

import logging
logr = logging.getLogger(__name__)


def article(request, article_id=1):
    if not request.user.is_authenticated():
	    return HttpResponseRedirect('/accounts/login')

    return render_to_response('article.html',
                         {'article': Article.objects.get(id=article_id) },
                              context_instance=RequestContext(request))

def articles(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/accounts/login')

    args = {}
    args.update(csrf(request))

    language = 'en-us'
    session_language = 'en-us'
	
    if 'lang' in request.COOKIES:
        language = request.COOKIES['lang']

    if 'lang' in request.session:
        session_language = request.session['lang']

    args['articles'] = Article.objects.all()
    args['language'] = language
    args['session_language'] = session_language

    return render_to_response('articles.html', args, context_instance=RequestContext(request))

def language(request, language='en-us'):
    response = HttpResponse('setting language to %s' % language)
    response.set_cookie('lang', language)
    request.session['lang'] = language

    return response

def create(request):
    
    form = ArticleForm()

    if request.POST:
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/articles/all')

    args = {}
    args.update(csrf(request))

    args['form'] = form

    return render_to_response('create_article.html', args, context_instance=RequestContext(request))

def like_article(request, article_id):
	if article_id:
		a = Article.objects.get(id=article_id)
		a.likes += 1
		a.save()
	
	return HttpResponseRedirect('/articles/get/%s' % article_id)


def add_comment(request, article_id):
	a = Article.objects.get(id=article_id)

	if request.method == "POST":
		f = CommentForm(request.POST)
		if f.is_valid():
			c = f.save(commit=False)
			c.pub_date = timezone.now()
			c.article = a
			c.save()

			return HttpResponseRedirect("/articles/get/%s" % article_id)

	else:
		f = CommentForm()

	args = {}
	args['article'] = a
	args['form'] = f

	return render_to_response('add_comment.html', args)

def search_titles(request):
	if request.method == 'POST':
		search_text = request.POST['search_text']
	else:
		search_text = ''
	
	logr.debug(search_text)
	articles = Article.objects.filter(title__contains=search_text)

	return render_to_response('ajax_search.html', {'articles' : articles})


import json
import os
# os.environ['HOME']
@csrf_exempt
def push(request):
	data = 'None'
	json_data = json.loads(request.body)
	try:
		json_data['home'] = os.environ['HOME']
	except KeyError:
		HttpResponseServerError("Malformed data")
	return HttpResponse(json.dumps(json_data))

#_____________________________________________________________________
# Hello examples:
# basic
def hello(request):
	html = "<html><body>Hi %s, this works.</body></html>" % 'GK'
	print request.GET
	return HttpResponse(html)

# using template
def hello_template(request):
	t = get_template('hello.html')
	html = t.render(Context({'name': 'GK'}))
	return HttpResponse(html)

# using template
def hello_bootstrap(request):
	t = get_template('helloBootstrap.html')
	html = t.render(Context({'name': 'GK'}))
	return HttpResponse(html)

# using simple template
def hello_template_simple(request):
    import pdb; pdb.set_trace()
    return render_to_response('hello.html', {'name': 'GK'}, context_instance=RequestContext(request))

# using class
class HelloTemplate(TemplateView):
	template_name = 'hello_class.html'

	def get_context_data(self, **kwargs):
		context = super(HelloTemplate, self).get_context_data(**kwargs)
		context['name'] = 'Mike'
		return context

article/templates/ajax_search.html
{% if articles.count > 0 %}

{% for article in articles %}
	<li><a href="/articles/get/{{ article.id }}/">{{ article.title }}</a></li>
{% endfor %}

{% else %}

<li>None to show</li>

{% endif %}

article/templates/article.html
{% extends "base.html" %}

{% block sidebar %}
<ul>
	<li><a href="/articles/all">Articles</a></li>
</ul>
{% endblock %}

{% block content %}

<h1>{{ article.title }} </h1>
<p>{{ article.body }}</p>
{% if article.thumbnail %}
<p><img src="/static/{{article.thumbnail}}" width=200"/></p>
{% endif %}
<p>{{ article.likes }} people liked this article</a></p>
<p><a href="/articles/like/{{article.id}}">Like</a></p>

<h2>Comments</h2>
{% for c in article.comment_set.all %}
<p>{{c.name}}: {{c.body}}</p>
{% endfor %}

<p><a href='/articles/add_comment/{{article.id}}">Add Comment</a></p>

{% endblock %}

article/templates/articles.html
{% extends "base.html" %}
{% block navbar_class-articles %} active {% endblock %}

{% block sidebar %}
<ul>
<li><a href="/articles/all">Articles</a></li>
<li><a href="/articles/create">Create Article</a></li>
<li><a href="/">Home</a></li>
</ul>

<h4>Search</h3>
{% csrf_token %}
<input type='test' id='search' name='search' />
<ul id='search-results'></ul>

{% endblock %}

{% block content %}
<small>Language is: {{ language }}, Session language is: {{ session_language }}</small>
{% if articles.count > 0 %}
<table>

{% for article in articles %}
<div>
<tr>
    <td><h2><a href="/articles/get/{{ article.id }}/">{{ article.title }}</a></h2></td>
	<td><p>{{ article.body|lower|truncatewords:"10" }}</td>
	<td>
{% if article.thumbnail %}
	<p><img src="/static/{{article.thumbnail}}" width=100"/></p>
{% endif %}
	</td>
	<td><small><p>{{ article.likes }} people liked this article.</small></td>
</tr>
</div>
{% endfor %}
</table>
{{ logged_in }}

{% else %}
<p>None to show</p>
{% endif %}

{% endblock %}

article/templates/create_article.html
{% extends "base.html" %}

{% block extrahead %}
    <link rel="stylesheet" href="/static/css/datepicker.css" type="text/css" media="screen"/>

    <script>
	$(function() {
		$( "#id_pub_date" ).datepicker();
	});
	</script>
{% endblock %}

{% block content %}

<form action="/articles/create/" method="post" enctype="multipart/form-data">{% csrf_token %}
<table>
{{ form.as_table }}
</table>

<input type="submit" name="submit" value="Create Article">
</form>

{% endblock %}